name: Shutdown Command
description: Shut down a bot through the Master bot.
active: false
class: Shutdown
key: shutdown
aliases:
  - sd
  - shut
cooldown:
  global: 0
  user: 0
authorization:
  enabledInDirectMessages: true
  accessEminence: Joker
clients: '*'
directory: >-
  /Users/kserebour/Personal/Estrella/node_modules/lavenza/core/talents/master/hooks/Commands/Shutdown
